#!/usr/bin/env python3
"""Build a complete Tegra RCM command image for fusee-rp2040."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class RcmLayout:
    usb_packet_size: int = 0x1000
    command_payload_offset: int = 680
    rcm_payload_addr: int = 0x40010000
    payload_start_addr: int = 0x40010E40
    stack_spray_start: int = 0x40014E40
    stack_spray_end: int = 0x40017000
    rcm_max_length: int = 0x30298


DEFAULT_LAYOUT = RcmLayout()


class RcmImageError(ValueError):
    """Raised when an RCM image cannot be generated safely."""


def align_up(value: int, alignment: int) -> int:
    return (value + alignment - 1) & ~(alignment - 1)


def _validate_layout(layout: RcmLayout, intermezzo_size: int) -> None:
    if layout.usb_packet_size <= 0 or layout.usb_packet_size & (layout.usb_packet_size - 1):
        raise RcmImageError("USB packet size must be a power of two")
    if layout.rcm_payload_addr + intermezzo_size > layout.payload_start_addr:
        raise RcmImageError("intermezzo overlaps the final payload start address")
    if layout.stack_spray_start < layout.payload_start_addr:
        raise RcmImageError("stack spray starts before the final payload")
    if layout.stack_spray_end < layout.stack_spray_start:
        raise RcmImageError("stack spray end is before stack spray start")
    if (layout.stack_spray_end - layout.stack_spray_start) % 4:
        raise RcmImageError("stack spray range must be word aligned")


def build_rcm_image(payload: bytes, intermezzo: bytes, layout: RcmLayout = DEFAULT_LAYOUT) -> bytes:
    """Return a padded RCM image ready to write to endpoint 0x01."""

    _validate_layout(layout, len(intermezzo))

    image = bytearray(layout.rcm_max_length.to_bytes(4, "little"))
    image.extend(b"\0" * (layout.command_payload_offset - len(image)))

    image.extend(intermezzo)
    image.extend(b"\0" * (layout.payload_start_addr - (layout.rcm_payload_addr + len(intermezzo))))

    payload_before_spray = layout.stack_spray_start - layout.payload_start_addr
    image.extend(payload[:payload_before_spray])
    if len(payload) < payload_before_spray:
        image.extend(b"\0" * (payload_before_spray - len(payload)))

    stack_spray_len = layout.stack_spray_end - layout.stack_spray_start
    image.extend(layout.rcm_payload_addr.to_bytes(4, "little") * (stack_spray_len // 4))

    if len(payload) > payload_before_spray:
        image.extend(payload[payload_before_spray:])

    unpadded_size = len(image)
    padded_size = align_up(unpadded_size, layout.usb_packet_size)
    if padded_size > layout.rcm_max_length:
        raise RcmImageError(
            "RCM image is too large: "
            f"{padded_size} bytes padded, max is {layout.rcm_max_length} bytes"
        )

    image.extend(b"\0" * (padded_size - unpadded_size))
    return bytes(image)


def format_c_header(
    image: bytes,
    payload_path: Path,
    intermezzo_path: Path,
    symbol: str,
    section: str,
    layout: RcmLayout = DEFAULT_LAYOUT,
) -> str:
    lines = [
        "/* Generated by tools/build_rcm_image.py. */",
        "#include <pico/platform.h>",
        "#include <stdint.h>",
        "",
        f"#define RCM_IMAGE_LEN {len(image)}u",
        f"#define RCM_IMAGE_USB_PACKET_SIZE {layout.usb_packet_size}u",
        f"#define RCM_IMAGE_MAX_LENGTH {layout.rcm_max_length}u",
        "",
        f"/* payload: {payload_path.as_posix()} */",
        f"/* intermezzo: {intermezzo_path.as_posix()} */",
        f"const uint8_t __in_flash(\"{section}\") {symbol}[] = {{",
    ]

    for offset in range(0, len(image), 16):
        chunk = image[offset : offset + 16]
        byte_list = ", ".join(f"0x{byte:02X}" for byte in chunk)
        lines.append(f"    {byte_list},")

    lines.extend(["};", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a complete RCM image C include.")
    parser.add_argument("--payload", required=True, type=Path, help="final payload binary")
    parser.add_argument("--intermezzo", required=True, type=Path, help="intermezzo relocator binary")
    parser.add_argument("--output", required=True, type=Path, help="generated C include path")
    parser.add_argument("--symbol", default="rcm_image", help="C array symbol name")
    parser.add_argument("--section", default="payloads", help="RP2040 flash section name")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    payload = args.payload.read_bytes()
    intermezzo = args.intermezzo.read_bytes()
    image = build_rcm_image(payload, intermezzo)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        format_c_header(image, args.payload, args.intermezzo, args.symbol, args.section),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
